# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('polls', '0023_auto_20160114_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_votes',
            field=models.ManyToManyField(blank=True, related_name='choices', to='polls.ChoiceVote'),
        ),
        migrations.AlterField(
            model_name='choicevote',
            name='choice',
            field=models.ManyToManyField(blank=True, to='polls.Choice'),
        ),
    ]
